---
## Install letsencrypt ruby user and Gem
- user:
    name: '{{letsencrypt_user}}'
    shell: /bin/bash
    createhome: yes
- include: rvm.yml
- include: install_letsencrypt.yml
- include: seed_letsencrypt.yml
  when: letsencrypt_seed_file is defined


- apt: pkg=python-passlib
  when: "(nginx_basic_auth_users | length) > 0"
- htpasswd:
    path: "{{item.file}}"
    name: "{{item.name}}"
    password: "{{item.password}}"
    owner: root
    group: www-data
    mode: 0640
  name: 'nginx | create passwd files for basic auth protection'
  with_items: "{{nginx_basic_auth_users}}"


# Configure sites
- include: configure_sites.yml
  tags: [only_routings]
# Activate existing http sites
- meta: flush_handlers
  tags: [only_routings]
  name: "Reload nginx now if necessary"

- include: request_letsencrypt.yml
  tags: [only_routings]
- include: configure_ssl_sites.yml
  tags: [only_routings]


